### ISSUE TITLE
getting CORS issues on big files

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/decentralized_storage_backend#64] opened 2023-08-17 14:01 UTC
**Describe the bug**
I've been testing the front with big files, when I tried I get CORS issues. I think this is related to the FILE_UPLOAD_MAX_MEMORY_SIZE we have set on the app, or the lack of it. 

Can you @mariacarmina please take a look?

File tested: Attachmed
https://cartographicperspectives.org/index.php/journal/article/view/cp43-complete-issue/pdf

Response: 
<img width="958" alt="Screenshot 2023-08-17 at 09 32 18" src="https://github.com/oceanprotocol/decentralized_storage_backend/assets/13741335/6637a5fa-695a-4757-9cd9-bbd45979f917">

@jamiehewitt15 Can you please check if it's not an axios issue coming from dbsjs.

**Comment by mariacarmina** [comment] 2023-08-18 08:08
The `FILE_UPLOAD_MAX_MEMORY_SIZE` supports up to 2.5 Mb.
![image](https://github.com/oceanprotocol/decentralized_storage_backend/assets/50501033/2e4894cc-431f-4b4d-a87b-b8759f25ed06)

**Comment by EnzoVezzaro** [comment] 2023-08-18 12:02
can we increase it to 50 or 100mb to make some tests. I think some users will try to upload files bigger than that.

**Comment by mariacarmina** [comment] 2023-09-04 22:24
Closing this, because it is duplicate of #73.

**Closed** 2023-09-04 22:24 UTC
